// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLwLbeIQ6vBZciIk11DMripW3NlRbUyI',
    appId: '1:134790081856:web:9fe1b318fbc98327029ea5',
    messagingSenderId: '134790081856',
    projectId: 'smart-abc-1893a',
    authDomain: 'smart-abc-1893a.firebaseapp.com',
    databaseURL: 'https://smart-abc-1893a-default-rtdb.firebaseio.com',
    storageBucket: 'smart-abc-1893a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC95vjpuIXIM84nDuJtGF-ovrg-r8fPtYI',
    appId: '1:134790081856:android:fb43b1413e48f78a029ea5',
    messagingSenderId: '134790081856',
    projectId: 'smart-abc-1893a',
    databaseURL: 'https://smart-abc-1893a-default-rtdb.firebaseio.com',
    storageBucket: 'smart-abc-1893a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg3ef1pcFLDwXS1T6FUClIfAyi2WRrlEI',
    appId: '1:134790081856:ios:14bf6c4dc73faaf6029ea5',
    messagingSenderId: '134790081856',
    projectId: 'smart-abc-1893a',
    databaseURL: 'https://smart-abc-1893a-default-rtdb.firebaseio.com',
    storageBucket: 'smart-abc-1893a.appspot.com',
    androidClientId: '134790081856-j1tmtdglpueioganh8le4plo81jg7ofc.apps.googleusercontent.com',
    iosClientId: '134790081856-f3p5r171pg0p47m1fomdipn199eo7df1.apps.googleusercontent.com',
    iosBundleId: 'kim.willy.smartAbc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg3ef1pcFLDwXS1T6FUClIfAyi2WRrlEI',
    appId: '1:134790081856:ios:14bf6c4dc73faaf6029ea5',
    messagingSenderId: '134790081856',
    projectId: 'smart-abc-1893a',
    databaseURL: 'https://smart-abc-1893a-default-rtdb.firebaseio.com',
    storageBucket: 'smart-abc-1893a.appspot.com',
    androidClientId: '134790081856-j1tmtdglpueioganh8le4plo81jg7ofc.apps.googleusercontent.com',
    iosClientId: '134790081856-f3p5r171pg0p47m1fomdipn199eo7df1.apps.googleusercontent.com',
    iosBundleId: 'kim.willy.smartAbc',
  );
}
